# Generated by Django 3.0.1 on 2020-01-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200101_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='stats',
            field=models.TextField(blank=True),
        ),
    ]
