# Generated by Django 3.0.1 on 2019-12-29 22:25

import challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('stock_name', models.CharField(max_length=512)),
                ('stock_ticker', models.CharField(max_length=12)),
                ('stock_description', models.TextField()),
                ('window_date', models.DateTimeField()),
                ('id', models.BigIntegerField(default=challenge.models.make_pk, primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('historic_data', models.TextField()),
                ('statement_8k', models.FileField(upload_to='')),
                ('statement_10k', models.FileField(upload_to='')),
                ('statement_10q', models.FileField(upload_to='')),
                ('statement_13f_nt', models.FileField(upload_to='')),
                ('statement_13f_hr', models.FileField(upload_to='')),
                ('statement_13f_g', models.FileField(upload_to='')),
                ('statement_sd', models.FileField(upload_to='')),
            ],
        ),
    ]
