# Generated by Django 3.0.1 on 2020-01-01 03:18

import challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('is_premium', models.BooleanField(default=True)),
                ('stock_name', models.CharField(max_length=512)),
                ('stock_ticker', models.CharField(max_length=12)),
                ('stock_description', models.TextField()),
                ('window_date', models.DateTimeField()),
                ('id', models.BigIntegerField(default=challenge.models.make_pk, primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('historic_data', models.TextField()),
                ('statement_8k', models.FileField(blank=True, upload_to=challenge.models.Challenge.upload_path_handler)),
                ('statement_10k', models.FileField(blank=True, upload_to=challenge.models.Challenge.upload_path_handler)),
                ('statement_10q', models.FileField(blank=True, upload_to=challenge.models.Challenge.upload_path_handler)),
                ('statement_13f_hr', models.FileField(blank=True, upload_to=challenge.models.Challenge.upload_path_handler)),
                ('statement_13_g', models.FileField(blank=True, upload_to=challenge.models.Challenge.upload_path_handler)),
                ('statement_sd', models.FileField(blank=True, upload_to=challenge.models.Challenge.upload_path_handler)),
            ],
        ),
    ]
