# Generated by Django 3.0.1 on 2020-01-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='time_label',
            field=models.CharField(default='1 Year', max_length=16),
            preserve_default=False,
        ),
    ]
