# Generated by Django 3.0.1 on 2019-12-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='statement_10k',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='statement_10q',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='statement_13f_g',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='statement_13f_hr',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='statement_13f_nt',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='statement_8k',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='statement_sd',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
