# Generated by Django 3.0.1 on 2019-12-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20191230_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_13f_g',
            new_name='statement_13_g',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='statement_13f_nt',
        ),
    ]
