# Generated by Django 3.0.1 on 2020-01-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challenge_time_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='time_label',
            new_name='time_label_full',
        ),
        migrations.AddField(
            model_name='challenge',
            name='time_label_url',
            field=models.CharField(default='1_year', max_length=16),
            preserve_default=False,
        ),
    ]
