# Generated by Django 3.0.1 on 2020-01-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challenge_result_amount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='result_amount_percent',
            field=models.CharField(max_length=16),
        ),
    ]
