# Generated by Django 3.0.1 on 2020-01-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20200105_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
