# Generated by Django 3.0.1 on 2020-01-12 15:38

import challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20200107_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='display_id',
            field=models.BigIntegerField(db_index=True, default=challenge.models.make_pk, unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
