# Generated by Django 3.0.1 on 2020-01-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20200112_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='statement_10f_hr_tables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='statement_10k_tables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='statement_10q_tables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='statement_13_g_tables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='statement_8k_tables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='statement_sd_tables',
            field=models.TextField(blank=True),
        ),
    ]
