# Generated by Django 3.0.1 on 2020-01-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20200128_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_10f_hr_tables',
            new_name='statement_10f_hr_summary',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_10k_tables',
            new_name='statement_10k_summary',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_10q_tables',
            new_name='statement_10q_summary',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_13_g_tables',
            new_name='statement_13_g_summary',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_8k_tables',
            new_name='statement_8k_summary',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_sd_tables',
            new_name='statement_sd_summary',
        ),
    ]
