# Generated by Django 3.0.1 on 2020-01-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20200128_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='statement_10f_hr_summary',
            new_name='statement_13f_hr_summary',
        ),
    ]
