# Generated by Django 3.0.1 on 2020-01-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20200128_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='statement_10k_summary',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='statement_10q_summary',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='statement_13_g_summary',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='statement_13f_hr_summary',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='statement_8k_summary',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='statement_sd_summary',
        ),
    ]
